### ISSUE TITLE
500 error when trying to send email

### ISSUE THREAD

**Issue by gerboland** [PythonIreland/broadgauge#10]
On the "Contact" page, entering valid information, I get:

127.0.0.1:35853 - - [14/Jun/2015 19:01:10] "HTTP/1.1 GET /contact" - 200 OK
Traceback (most recent call last):
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/home/gerry/dev/play/pythonireland/broadgauge/broadgauge/views/home.py", line 61, in POST
    to=web.config.contact_email,
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/utils.py", line 76, in __getattr__
    raise AttributeError, k
AttributeError: 'contact_email'

**Comment by bmihovski** [comment]
This pull request should fix that issue https://github.com/PythonIreland/broadgauge/pull/26

**Comment by ghost** [comment]
Is this related? I attempted to add a new comment on a workshop, which triggered the following stack trace:

```
0.0 (1): SELECT * FROM workshop WHERE id = '1'
0.0 (2): SELECT * FROM users WHERE email = 'ben@fluidlogic.org'
0.0 (3): INSERT INTO comment (comment, author_id, workshop_id) VALUES ('This is a new comment', 1, 1); SELECT currval('comment_id_seq')
0.0 (4): SELECT * FROM comment WHERE id = 2
0.0 (5): SELECT * FROM workshop WHERE id = 1
0.0 (6): SELECT * FROM organization WHERE id = 1
0.0 (7): SELECT users.*, role FROM users JOIN organization_members ON organization_members.user_id=users.id WHERE organization_members.org_id=1
0.0 (8): SELECT * FROM comment WHERE workshop_id = 1 ORDER BY created
0.0 (9): SELECT * FROM users WHERE id = 1
0.0 (10): SELECT * FROM users WHERE id = 1
set([<Storage {'username': u'benklaasen', 'city': u'Dublin', 'github': u'benklaasen', 'name': u'Ben Klaasen', 'bio': None, 'created': datetime.datetime(2015, 6, 21, 13, 51, 45, 761227), 'is_trainer': True, 'id': 1, 'website': None, 'phone': u'+353872212936', 'avatar_url': u'https://avatars.githubusercontent.com/u/651495?v=3', 'is_admin': None, 'email': u'ben@fluidlogic.org'}>, <bound method Workshop.get_trainer of <Storage {'status': u'confirmed', 'description': u'Bacon ipsum dolor amet pancetta tail leberkas shoulder, salami frankfurter bresaola biltong ham hock shankle kevin ribeye ham. Ham hock sirloin biltong porchetta. Spare ribs short ribs filet mignon, ball tip leberkas boudin bacon rump beef strip steak prosciutto bresaola swine capicola. Corned beef picanha turkey spare ribs, porchetta ham hock salami chicken pork. Strip steak tri-tip rump, picanha leberkas fatback filet mignon.\r\n\r\nRibeye pancetta bresaola salami brisket swine corned beef fatback kielbasa. Venison cupim biltong, chuck pork belly picanha pork chop rump brisket meatball fatback. Cow ribeye brisket prosciutto bacon porchetta t-bone. Drumstick turducken tenderloin t-bone, ham strip steak beef ribs shank ground round sausage pastrami fatback. Swine beef ribs ribeye drumstick biltong. Hamburger tri-tip capicola turducken swine prosciutto boudin jerky tongue. Tri-tip kevin brisket, ribeye frankfurter prosciutto alcatra pork picanha turducken.\r\n\r\nBall tip tail beef chicken pork chop. Pork chop pancetta porchetta ball tip, alcatra ribeye tenderloin jowl frankfurter shank pork belly tail. Ham hock shoulder pig ribeye pork loin ball tip. Meatball boudin flank spare ribs bacon alcatra beef strip steak beef ribs tongue leberkas ham cow. Pig picanha frankfurter rump pork landjaeger. Short ribs pork andouille fatback, tenderloin shoulder strip steak swine.\r\n\r\nHam hock pork loin t-bone, cupim pancetta flank spare ribs. Meatball tenderloin shankle kielbasa swine chicken corned beef, beef ribs boudin alcatra. Ground round swine chicken shoulder ribeye. Turkey sirloin andouille ball tip rump prosciutto, tongue fatback pig flank hamburger picanha. Meatball corned beef flank short ribs, sirloin bresaola porchetta. Beef biltong flank, shank sirloin rump t-bone venison.\r\n\r\nBeef t-bone filet mignon corned beef, tenderloin ham sirloin bacon kielbasa leberkas flank rump. Corned beef rump venison beef sausage bresaola andouille doner turkey spare ribs filet mignon. Chicken salami beef ribs, picanha spare ribs tail ground round kielbasa flank. Venison short loin filet mignon beef pastrami ground round salami.', 'title': u'Finding your way in a crazy world', 'trainer_id': 1, 'org_id': 1, 'expected_participants': 30, 'date': datetime.date(2015, 7, 1), 'id': 1}>>])
0.0 (11): SELECT * FROM users WHERE id = 1
2015-06-21 15:05:58,272 [WARNING] smtp_server not configured, mail won't be sent.
Traceback (most recent call last):
  File "/home/ben/src/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/home/ben/src/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/ben/src/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/home/ben/src/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/home/ben/src/broadgauge/broadgauge/views/workshops.py", line 59, in POST
    return self.POST_add_comment(workshop, i)
  File "/home/ben/src/broadgauge/broadgauge/views/workshops.py", line 109, in POST_add_comment
    signals.new_comment.send(comment)
  File "/home/ben/src/broadgauge/local/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/ben/src/broadgauge/broadgauge/actions.py", line 76, in on_new_comment
    to=u.email,
AttributeError: 'function' object has no attribute 'email'

127.0.0.1:36977 - - [21/Jun/2015 15:05:58] "HTTP/1.1 POST /workshops/1" - 500 Internal Server Error
```

In particular, check out the message "AttributeError: 'function' object has no attribute 'email'"

**Comment by bmihovski** [comment]
2015-06-21 15:05:58,272 [WARNING] smtp_server not configured, mail won't be sent.
This warning is related to the missing (commented out) smtp settings. We need separate issue according to that.

**Comment by ghost** [comment]
Thanks, I'll log this as a new issue.
