### ISSUE TITLE
Trying to associate the same member to an organisation causes a 500 error

### ISSUE THREAD

**Issue by gerboland** [PythonIreland/broadgauge#15]
1. Create a Trainer account
2. With another account, create an Organization
3. Associate the trainer account from step 1 with the Org.
4. Try associating it again. You'll get:

ERR: INSERT INTO organization_members (user_id, role, org_id) VALUES (1, 'Dad', 1); SELECT currval('organization_members_id_seq')
Traceback (most recent call last):
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/home/gerry/dev/play/pythonireland/broadgauge/broadgauge/views/orgs.py", line 58, in POST
    org.add_member(member, i.role)
  File "/home/gerry/dev/play/pythonireland/broadgauge/broadgauge/models.py", line 143, in add_member
    get_db().insert("organization_members", org_id=self.id, user_id=user.id, role=role)
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/db.py", line 788, in insert
    self._db_execute(db_cursor, sql_query)
  File "/home/gerry/dev/play/pythonireland/broadgauge/local/lib/python2.7/site-packages/web/db.py", line 591, in _db_execute
    out = cur.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "organization_members_org_id_user_id_key"
DETAIL:  Key (org_id, user_id)=(1, 1) already exists.

**Comment by andrewmccarthy** [comment]
The IntegrityError exception comes from [psycopg2](http://initd.org/psycopg/), and is a straightforward error that you're inserting a duplicate key. From https://stackoverflow.com/questions/12490172/integrityerror-distinguish-between-unique-constraint-and-not-null-violations you can catch this exception and check that `exception.pgcode==23505`. Apparently 23505 is the [Postgres error code](http://www.postgresql.org/docs/current/static/errcodes-appendix.html) that means `unique_violation`.

Options are either
- Catch the IntegrityError exception and ignore it if pgcode=23505 (which will only work if the database is Postgres)

or
- Check before the insert that the entry isn't always there. (Race condition possible?)

**Comment by andrewmccarthy** [comment]
Having thought more about it, catching the IntegrityError and ignoring it brings a direct dependency on psycopg2, as well as tying the application to Postgres only, so I'm not happy with that.

We can easily check the user isn't there already with:

``` python
    def add_member(self, user, role):
        if not self.is_member(user):
            get_db().insert("organization_members", org_id=self.id, user_id=user.id, role=role)
```

The only concern is that the role passed to `add_member` may be different to the existing one. This code snippet would ignore the new role, whereas we may want to update the role.

The alternative is to resolve this at a "higher" level entirely, i.e. in the view where we can deliver a "member already exists" error to the user.
