### ISSUE TITLE
run.py failing with exception AttributeError: 'NoneType' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by bmihovski** [PythonIreland/broadgauge#59]
The web application can't be started because of error during run time.

When I run run.py I am receiving exception like this:

Traceback (most recent call last):
  File "/Users/boyanmihovski/git/broadgauge/run.py", line 14, in <module>
    main()
  File "/Users/boyanmihovski/git/broadgauge/run.py", line 11, in main
    main()
  File "/Users/boyanmihovski/git/broadgauge/broadgauge/main.py", line 78, in main
    web.config['base_url']=web.config.get('base_url').rstrip('/')
AttributeError: 'NoneType' object has no attribute 'rstrip'

**Comment by bmihovski** [comment]
Intermitted issue.
